import React from 'react';
import type { Metadata } from "next";
import 'antd/dist/reset.css';
import "./globals.css";
import AppLayout from "./layout/index";


export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body data-theme="light">
        <AppLayout content={children} />
      </body>
    </html>
  );
}
